language: android

notifications:
  email: false

sudo: false

jdk:
  - openjdk7

android:
  components:
    - tools
    # Used for :app
    - build-tools-23.0.2
    - android-23
    # Used for :volley
    - build-tools-22.0.1
    - android-22
    # Extra dependencies
    - extra-android-m2repository
    # Emulator image
    - sys-img-armeabi-v7a-android-23
  licences:
    - 'android-sdk-license-.+'

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest

# Caching setup
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/