language: android

notifications:
  email: false

sudo: false

jdk:
  - openjdk7

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - android-22
    - extra-android-m2repository

install: true

script: ./gradlew build connectedCheck